name: Build Linux Distribution (ubuntu-22.04)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Download Liberica NIK
        run: |
          download_url="https://download.bell-sw.com/vm/23.1.2/bellsoft-liberica-vm-full-openjdk21.0.2+14-23.1.2+1-linux-amd64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Liberica NIK
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: 21
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          architecture: x64

      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: nativeCompile

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Distribution
          path: build/native/nativeCompile