name: Build Windows Distribution (windows-2022)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Download Liberica NIK
        run: |
          C:\msys64\usr\bin\wget.exe -O ${{ runner.temp }}\java_package.zip "https://download.bell-sw.com/vm/23.1.2/bellsoft-liberica-vm-full-openjdk21.0.2+14-23.1.2+1-windows-amd64.zip"

      - name: Set up Liberica NIK
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: 21
          jdkFile: ${{ runner.temp }}/java_package.zip
          architecture: x64

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: nativeCompile

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Distribution
          path: build/native/nativeCompile